import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import { useRouter } from "next/router";
import { ButtonBase } from "@reusejs/react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" min-h-screen">
        <div className={styles.description}>Helloo blogs:{router.query.id}</div>
        {/* <button className="bg-blue-600">Click here</button> */}
        <ButtonBase
          label="testDemo"
          buttonBaseClasses={{
            backgroundColor: "bg-blue-600",
            borderRadius: "rounded",
          }}
          onClick={() => {
            console.log("Clicked");
          }}
        />
      </main>
    </>
  );
}
